import "./globals.css"
import { Providers } from "./providers"
import Footer from "@/components/footer"
import LightRay from "@/components/light-ray"
import Navbar from "@/components/navbar"
import { Analytics } from "@vercel/analytics/next"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { Provider } from "react-wrap-balancer"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Provider>
                    <Providers>
                        <div className="container mx-auto max-w-3xl font-[family-name:var(--font-geist-mono)] px-6">
                            <LightRay />
                            <Navbar />
                            {children}
                            <Footer />
                        </div>
                    </Providers>
                </Provider>
                <Analytics />
            </body>
        </html>
    )
}
